config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :events
  resources :participants
  resources :comments
  get "my_participations", action: :user_index, controller: "participants"
  get "users/:id", action: :show, controller: "users/users", as: :get_user
  resources :notifications
  post "mark_as_read/:id", action: :mark_as_read, controller: "notifications", as: :mark_as_read
  post "mark_as_unread/:id", action: :mark_as_unread, controller: "notifications", as: :mark_as_unread


  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout",
    registration: "signup"
  },
  controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    users: "users/users"
  }

  # post "api/v1/users/login", to: "api/v1/users/sessions#new"
  # post "api/v1/users/signup", to: "api/v1/users/registrations#new"

  scope "/api", defaults: { format: :json } do
    scope "/v1" do
      scope "/users" do
        devise_for :users, as: :user_api, path: "", path_names: {
          sign_in: "login", sign_out: "logout", registration: "signup"
        }, controllers: {
          registrations: "api/v1/users/registrations",
          sessions: "api/v1/users/sessions"
        }
        devise_scope :user do
          get "users/current", to: "api/v1/users/sessions#show"
        end

        resources :pages, only: %i[index]
      end

      resources :events, as: :api_events, controller: "api/v1/events/events"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!, only: %i[ index ]

  def index
    @notifications = current_user.notifications
    # @notifications.each do |notification|
    #   notification.update(read: true)
    # end
    # @notifications.first.mark_as_unread
  end

  def mark_as_read
    notification = Noticed::Notification.find(notification_params[:id])
    notification.mark_as_read
    redirect_to notifications_url
  end

  def mark_as_unread
    notification = Noticed::Notification.find(notification_params[:id])
    notification.mark_as_unread
    redirect_to notifications_url
  end

  private
  def notification_params
    params.permit(:id)
  end
end

app/views/notifications/index.html.erb
<div class="m-2">
  <h1>
    Notifications
  </h1>
  <div>
    <% if current_user.notifications.any? %>
      <div>
        <% current_user.notifications.newest_first.each do |notification| %>
          <div class="box m-3">
            <% if notification.read? %>
              <div class="float-end">
                <%= button_to "Mark as unread", mark_as_unread_path(id: notification.id), method: :post, class: "btn btn-outline-primary" %>
              </div>
            <% else %>
              <div class="float-end">
                <p class="badge rounded-pill text-bg-primary mx-2 px-2">
                  Unread
                </p>
                <%= button_to "Mark as read", mark_as_read_path(id: notification.id), method: :post, class: "btn btn-outline-primary" %>
              </div>
            <% end %>
            <p>
              <%= notification.params[:message] %>
            </p>
            <p>
              <%= notification.created_at %>
            </p>
            <%= link_to "Go to Event", event_path(notification.event_id), method: :get %>
          </div>
        <% end %>
      </div>
    <% else %>
      <p>
        You have no notifications
      </p>
    <% end %>
  </div>
</div>