config/routes.rb
Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :events
  resources :participants
  resources :comments
  get "my_participations", action: :user_index, controller: "participants"
  get "users/:id", action: :show, controller: "users/users", as: :get_user
  resources :notifications
  post "mark_as_read/:id", action: :mark_as_read, controller: "notifications", as: :mark_as_read
  post "mark_as_unread/:id", action: :mark_as_unread, controller: "notifications", as: :mark_as_unread


  devise_for :users, path: "", path_names: {
    sign_in: "login",
    sign_out: "logout",
    registration: "signup"
  },
  controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations",
    users: "users/users"
  }

  # post "api/v1/users/login", to: "api/v1/users/sessions#new"
  # post "api/v1/users/signup", to: "api/v1/users/registrations#new"

  scope "/api", defaults: { format: :json } do
    scope "/v1" do
      scope "/users" do
        devise_for :users, as: :user_api, path: "", path_names: {
          sign_in: "login", sign_out: "logout", registration: "signup"
        }, controllers: {
          registrations: "api/v1/users/registrations",
          sessions: "api/v1/users/sessions"
        }
        devise_scope :user do
          get "users/current", to: "api/v1/users/sessions#show"
        end

        resources :pages, only: %i[index]
      end

      resources :events, as: :api_events, controller: "api/v1/events/events"
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Fomo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top">
      <div class="container-fluid">
        <%= link_to 'FOMO', root_path, class:"nav-link" %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse  d-flex justify-content-between" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'All Events', events_path, class:"nav-link" %>
            </li>
            <% if current_user %>
              <li class="nav-item">
                <%= link_to 'My Saved Events', my_participations_path, class:"nav-link" %>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to notifications_path, class:"nav-link" do %>
                  <svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 -960 960 960" width="24px" fill="#5f6368"><path d="M160-200v-80h80v-280q0-83 50-147.5T420-792v-28q0-25 17.5-42.5T480-880q25 0 42.5 17.5T540-820v28q80 20 130 84.5T720-560v280h80v80H160Zm320-300Zm0 420q-33 0-56.5-23.5T400-160h160q0 33-23.5 56.5T480-80ZM320-280h320v-280q0-66-47-113t-113-47q-66 0-113 47t-47 113v280Z"/></svg>
                  <%= current_user.notifications.unread.size if current_user.notifications.unread.any? %>
                <% end %>
              </li>
            <% end %>
            <li class="nav-item dropdown">
                <% if user_signed_in? %>
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Welcome, <%= current_user.name %>
                  </a>
                  <ul class="dropdown-menu">
                    <%= link_to 'Profile', get_user_path(current_user), data: { turbo: false }, class:'dropdown-item' %>
                    <%= link_to 'Edit my user', edit_user_registration_path, data: { turbo: false }, class:'dropdown-item' %>
                    <%= button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false, turbo_method: :delete, }, class:'dropdown-item' %>
                  </ul>
                <% else %>
                  <%= link_to 'Sign in', new_user_session_path, class:"nav-link" %>
                <% end %>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class='my-2'>
      <% if flash[:notice] %>
        <div class="notice alert alert-light mx-2" role><%= notice %></div>
      <% end %>
      <% if flash[:alert] %>
        <div class="alert alert-danger mx-2"><%= alert %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>